// Code generated by internal/control/gen; DO NOT EDIT.

package control

import (
	"time"
)

const (
	WireSchemaFingerprint = "f72603915fb9dde22235bf3ff9dec46801e4d9380c6e8ac8de1c35db505f0d54"
	WireBuild             = "com.yasyf.cc-squash.control/" + WireSchemaFingerprint + "/v1"
)

const StatusSchemaVersion = 1

type Op string

const (
	OpStatus Op = "status"
	OpMint   Op = "mint"
	OpKill   Op = "kill"
	OpShadow Op = "shadow"
	OpGc     Op = "gc"
)

type EmptyRequest struct{}

type ToggleRequest struct {
	On bool `json:"on"`
}

type HealthDetail struct {
	RuntimeBuild string `json:"runtime_build"`
}

type StatusSnapshot struct {
	SchemaVersion int       `json:"schema_version"`
	Version       string    `json:"version"`
	GeneratedAt   time.Time `json:"generated_at"`
	ProxyPort     int       `json:"proxy_port"`
	ProxyMCPort   int       `json:"proxy_mcp_port"`
	ProxyPID      int       `json:"proxy_pid"`
	Sessions      int       `json:"sessions"`
	Kill          bool      `json:"kill"`
	Shadow        bool      `json:"shadow"`
}

type Response struct {
	OK      bool            `json:"ok"`
	Error   string          `json:"error,omitempty"`
	Port    int             `json:"port,omitempty"`
	MCPPort int             `json:"mcp_port,omitempty"`
	Token   string          `json:"token,omitempty"`
	Status  *StatusSnapshot `json:"status,omitempty"`
	Kill    bool            `json:"kill,omitempty"`
	Shadow  bool            `json:"shadow,omitempty"`
}
