// Code generated by internal/control/gen; DO NOT EDIT.

package control

import (
	"time"
)

const (
	WireSchemaFingerprint = "7e33435fedbf3ee0e1f9f70910c56839a826e6b9a134f152e2144b10caa3c53f"
	WireBuild             = "com.yasyf.cc-squash.control/" + WireSchemaFingerprint + "/v1"
)

const StatusSchemaVersion = 1

type Op string

const (
	OpRuntimeHealth Op = "cc-squash.runtime.health"
	OpStatus        Op = "status"
	OpMint          Op = "mint"
	OpKill          Op = "kill"
	OpShadow        Op = "shadow"
	OpGc            Op = "gc"
)

type EmptyRequest struct{}

type ToggleRequest struct {
	On bool `json:"on"`
}

type RuntimeState string

const (
	RuntimeStateHealthy  RuntimeState = "healthy"
	RuntimeStateDegraded RuntimeState = "degraded"
	RuntimeStateFailed   RuntimeState = "failed"
)

type RuntimeHealth struct {
	RuntimeBuild      string       `json:"runtime_build"`
	RuntimeProtocol   int          `json:"runtime_protocol"`
	PID               int          `json:"pid"`
	ProcessGeneration string       `json:"process_generation"`
	Ready             bool         `json:"ready"`
	State             RuntimeState `json:"state"`
	Draining          bool         `json:"draining"`
	Busy              bool         `json:"busy"`
}

type StatusSnapshot struct {
	SchemaVersion int       `json:"schema_version"`
	Version       string    `json:"version"`
	GeneratedAt   time.Time `json:"generated_at"`
	ProxyPort     int       `json:"proxy_port"`
	ProxyMCPort   int       `json:"proxy_mcp_port"`
	ProxyPID      int       `json:"proxy_pid"`
	Sessions      int       `json:"sessions"`
	Kill          bool      `json:"kill"`
	Shadow        bool      `json:"shadow"`
}

type Response struct {
	OK            bool            `json:"ok"`
	Error         string          `json:"error,omitempty"`
	Port          int             `json:"port,omitempty"`
	MCPPort       int             `json:"mcp_port,omitempty"`
	Token         string          `json:"token,omitempty"`
	RuntimeHealth *RuntimeHealth  `json:"runtime_health,omitempty"`
	Status        *StatusSnapshot `json:"status,omitempty"`
	Kill          bool            `json:"kill,omitempty"`
	Shadow        bool            `json:"shadow,omitempty"`
}
